version: "3.4"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"
  bot:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  nats:
    image: nats:2.1.9
    ports:
      - "4222:4222"
      - "8222:8222"